### ISSUE TITLE
Error Menu handle ff8970 is invalid (error 4)

### ISSUE THREAD

**Issue by crashzk** [nuclearsilo583/zephyrus-store-preview-new-syntax#29]
I'm getting the following errors in the server logs:
```
L 09/01/2021 - 00:12:26: [SM] Exception reported: Menu handle ff8970 is invalid (error 4)
L 09/01/2021 - 00:12:26: [SM] Blaming: store.smx
L 09/01/2021 - 00:12:26: [SM] Call stack trace:
L 09/01/2021 - 00:12:26: [SM]   [0] AddMenuItem
L 09/01/2021 - 00:12:26: [SM]   [1] Line 448, C:\Users\paulo\Desktop\csgo\addons\sourcemod\scripting\include\zephstocks.inc::AddMenuItemEx
L 09/01/2021 - 00:12:26: [SM]   [2] Line 95, store/gifts.sp::Gifts_OnMenu
L 09/01/2021 - 00:12:26: [SM]   [4] Call_Finish
L 09/01/2021 - 00:12:26: [SM]   [5] Line 2308, C:\Users\paulo\Desktop\csgo\addons\sourcemod\scripting\store.sp::DisplayItemMenu
L 09/01/2021 - 00:12:26: [SM]   [6] Line 2203, C:\Users\paulo\Desktop\csgo\addons\sourcemod\scripting\store.sp::MenuHandler_Store

L 09/01/2021 - 00:15:10: [SM] Exception reported: Menu handle ff8974 is invalid (error 4)
L 09/01/2021 - 00:15:10: [SM] Blaming: store.smx
L 09/01/2021 - 00:15:10: [SM] Call stack trace:
L 09/01/2021 - 00:15:10: [SM]   [0] AddMenuItem
L 09/01/2021 - 00:15:10: [SM]   [1] Line 448, C:\Users\paulo\Desktop\csgo\addons\sourcemod\scripting\include\zephstocks.inc::AddMenuItemEx
L 09/01/2021 - 00:15:10: [SM]   [2] Line 95, store/gifts.sp::Gifts_OnMenu
L 09/01/2021 - 00:15:10: [SM]   [4] Call_Finish
L 09/01/2021 - 00:15:10: [SM]   [5] Line 2308, C:\Users\paulo\Desktop\csgo\addons\sourcemod\scripting\store.sp::DisplayItemMenu
L 09/01/2021 - 00:15:10: [SM]   [6] Line 2104, C:\Users\paulo\Desktop\csgo\addons\sourcemod\scripting\store.sp::MenuHandler_Store
L 09/01/2021 - 00:15:10: [SM]   [8] Call_Finish
L 09/01/2021 - 00:15:10: [SM]   [9] Line 3001, C:\Users\paulo\Desktop\csgo\addons\sourcemod\scripting\store.sp::MenuHandler_Confirm

L 09/01/2021 - 03:39:45: [SM] Exception reported: Invalid timer handle cada13b2 (error 3)
L 09/01/2021 - 03:39:45: [SM] Blaming: store.smx
L 09/01/2021 - 03:39:45: [SM] Call stack trace:
L 09/01/2021 - 03:39:45: [SM]   [0] KillTimer
L 09/01/2021 - 03:39:45: [SM]   [1] Line 486, C:\Users\paulo\Desktop\csgo\addons\sourcemod\scripting\include\zephstocks.inc::ClearTimer
L 09/01/2021 - 03:39:45: [SM]   [2] Line 3668, C:\Users\paulo\Desktop\csgo\addons\sourcemod\scripting\store.sp::Store_DisconnectClient
L 09/01/2021 - 03:39:45: [SM]   [3] Line 1316, C:\Users\paulo\Desktop\csgo\addons\sourcemod\scripting\store.sp::OnClientDisconnect
L 09/01/2021 - 04:01:47: Error log file session closed.
```
**sm plugins list**
```
[SM] Listing 111 plugins:
  001 "Store - Trade System" (1.0) by Zephyrus
  002 "Rock The Vote" (1.10.0.6510) by AlliedModders LLC
  003 "CS:GO Multi1v1: Noscope round addon" (1.2.6) by Cruze
  004 "ServerAdvertisements3" (3.1.4) by ESK0
  005 "Server redirect" (1.3.1) by GAMMA CASE
  006 "Store - Dice gamble module" (1.2) by shanapu, nuclear silo
  007 "SM Franug Hats" (3.3.3) by Franc1sco franug
  008 "TecnoHard™ Ranks/Coins/Profiles" (1.1.0) by abnerfs
  009 "Store - Jackpot gamble module" (1.2) by shanapu, nuclear silo
  010 "Weapons & Knives" (1.7.3) by kgns | oyunhost.net
  011 "Fix Disconnect Reason" (1.0.0) by FroidGaming.net
  012 "Store Giveaway" (1.2) by nuclear silo
  013 "SourceBans++ Report Plugin" (1.7.0) by RumbleFrog, SourceBans++ Dev Team
  014 "Store - Bulletsparks item module" (1.0) by shanapu, nuclear silo
  015 "[ ZK Servidores™ ] Console Ads" (1.1) by biielzk, crashzk
  016 "Store - MVP sound item module" (1.0) by shanapu, nuclear silo
  017 "SM First Person View Models Interface" (3.2) by Franc1sco franug
  018 "[ANY] Chat Responder" (1.3.4) by Headline
  019 "SourceBans++ Discord" (1.7.0-49) by Kotik. Fork of RumbleFrog, SourceBans++ Dev Team.
  020 "Store - Player Skin Module (No ZR version)" (1.0) by nuclear silo
  021 "SourceBans++: SourceComms" (1.7.0) by Alex, SourceBans++ Dev Team
  022 "Basic Comm Control" (1.10.0.6510) by AlliedModders LLC
  023 "[Levels Ranks] Core" (v3.1.7 Beta 1) by RoadSide Romeo & Wend4r
  024 <Failed> "[LR] Module - ExStats GeoIP" (v3.1) by RoadSide Romeo
  025 "[LR] Module - Unusual Kills" (v3.1.6 SR2) by Wend4r
  026 "[LR] Module - ExStats Maps" (3.1 F1) by RoadSide Romeo
  027 "[LR] Module - ExStats Weapons" (v3.1) by RoadSide Romeo & Wend4r
  028 "[LR] Module - ExStats Hits" (v3.1) by Wend4r
  029 "[LR] Module - TOP by KDR" (v3.1.5) by Wend4r
  030 "Nextmap" (1.10.0.6510) by AlliedModders LLC
  031 "Store - Tracers Module" (1.0) by nuclear silo
  032 "CS:GO Multi1v1" (1.1.10-dev+220) by splewis
  033 "[ ZK Servidores™ ] High Ping Kicker" (1.1) by Dr. Api, crashzk
  034 "Map Nominations" (1.10.0.6510) by AlliedModders LLC
  035 "SwapTeam" (1.2.6fix) by MistaGee, Rogue, crashzk
  036 "Fix Hint Color Messages" (1.2.2 Franc1sco franug github version) by Phoenix (˙·٠●Феникс●٠·˙)
  037 "MapChooser" (1.10.0.6510) by AlliedModders LLC
  038 "AFK Manager" (4.3.0fix) by Rothgar
  039 "Store - Sound item module" (1.1) by shanapu, nuclear silo
  040 "SourceBans++: Admin Config Loader" (1.7.0) by AlliedModders LLC, SourceBans++ Dev Team
  041 "AntiDLL Handler" (1.7) by JDW
  042 "Store - Link item module" (1.0) by shanapu, nuclear silo
  043 "Basic Commands" (1.10.0.6510) by AlliedModders LLC
  044 "[DHooks] Block SM Plugins" (1.0.0) by Bara
  045 "SM Franug CSGO Sprays" (1.4.2) by Franc1sco Steam: franug, EMINEM
  046 "SM FPVMI - Custom Weapons Menu" (3.1) by Franc1sco franug
  047 "eItems" (0.10) by ESK0 (Original author: SM9)
  048 "Gloves" (1.0.5) by kgns | oyunhost.net
  049 "CS:GO Multi1v1: flashbangs addon" (1.1.10-dev+220) by splewis
  050 "Store - The Resurrection with preview rewritten compilable with SM 1.10 new syntax" (5.5.7) by Zephyrus, nuclear silo
  051 "[CS:GO] Weapon Stickers" (1.0.18) by quasemago and donut1k
  052 "SourceBans++: Bans Checker" (1.7.0) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  053 "CS:GO Multi1v1: He grenade battle round addon" (1.1) by Franc1sco franug
  054 "Sound Commands" (1.10.0.6510) by AlliedModders LLC
  055 "Store Grenade Skin" (1.0) by zephyrus, nuclear silo
  056 "Store - Admin / Vip Flags Fore Store" (1.0) by nuclear silo
  057 "Skybox" (1.01) by Deathknife
  058 "Chat-Processor" (2.2.3) by Drixevel
  059 "Store - Bullet impact item module" (1.0) by shanapu, nuclear silo
  060 "Store - Teambet gamble module" (1.1) by shanapu, nuclear silo
  061 "SourceBans++: Main Plugin" (1.7.0) by SourceBans Development Team, SourceBans++ Dev Team
  062 "Store - Roulette gamble module" (1.2) by shanapu, nuclear silo
  063 "Store - Crash gamble module" (2.1) by Emur, AiDN™, nuclear silo
  064 "[CSS/CS:GO] AbNeR ResetScore" (1.5fix) by AbNeR_CSS
  065 "Fun Commands" (1.10.0.6510) by AlliedModders LLC
  066 "store_item_lasersight.smx"
  067 "Thirdperson Mode" (1.0) by Zephyrus
  068 "CS:GO Multi1v1: knife round addon" (1.1.10-dev+220) by splewis
  069 "Store - Pet item module" (1.0) by nuclear silo
  070 "Admin Menu" (1.10.0.6510) by AlliedModders LLC
  071 "Valve items menu" (1.0) by Franc1sco franug
  072 "Store - Particle item module" (1.0) by shanapu, nuclear silo
  073 "Store - Crowns gamble module" (1.2) by shanapu, nuclear silo
  074 "[CS:GO] Custom MVP Anthem" (1.11) by Kento
  075 "NoBots Enforcer" (1.0) by Nikooo777
  076 "[SWGM] Command Listener" (1.2fix) by Someone, crashzk
  077 "Simple Stealth" (1.0) by Potatoz
  078 "Basic Info Triggers" (1.10.0.6510) by AlliedModders LLC
  079 "Anti-Flood" (1.10.0.6510) by AlliedModders LLC
  080 "Player Commands" (1.10.0.6510) by AlliedModders LLC
  081 "[ANY] Unrestricted FOV" (1.2.0) by Dr. McKay
  082 "Client Preferences" (1.10.0.6510) by AlliedModders LLC
  083 "Store Grenade Trail" (1.0) by zephyrus, nuclear silo
  084 "SM Voice Agents Enabler" (1.0) by Franc1sco franug
  085 "Store - Hats Module" (1.0) by nuclear silo
  086 "Store - Lootbox module" (1.5) by shanapu, nuclear silo
  087 "Admin File Reader" (1.10.0.6510) by AlliedModders LLC
  088 "Store - Colored Smoke Module" (1.0) by nuclear silo
  089 "SourceBans++: SourceSleuth" (1.7.0) by ecca, SourceBans++ Dev Team
  090 "[Lilac] Little Anti-Cheat" (1.7.1) by J_Tanzanite
  091 "[ANY] Gifts" (2.3) by Zephyrus
  092 "Basic Chat" (1.10.0.6510) by AlliedModders LLC
  093 "Store - Tracers Module" (1.0) by nuclear silo
  094 "Store - Chat Processor item module with Scoreboard Tag" (1.1) by nuclear silo, Mesharsky, AiDN™
  095 "Fun Votes" (1.10.0.6510) by AlliedModders LLC
  096 "Store - Info panel item module" (1.0) by shanapu, nuclear silo
  097 "Store - Voucher module" (1.2) by shanapu, nuclear silo
  098 "SM Franug CS:GO Agents Chooser" (1.2) by Franc1sco franug & Romeo
  099 "[Multi-1v1] Challenge" (1.1.5) by Headline
  100 "store_item_sprays.smx"
  101 "[CS:GO] Music Kits Valve" (1.9.1) by iEx, Kento, crashzk, northeaster, ByDexter, Emur
  102 "Store - Coinflip gamble module" (1.2) by shanapu, nuclear silo
  103 "Store - Bunny module" (1.0) by nuclear silo
  104 "Basic Votes" (1.10.0.6510) by AlliedModders LLC
  105 "[CSGO]Multi 1v1 - Deagle 1 Tap" (1.0) by S4muRaY'
  106 "Blackjack" (1.0) by HerrMagic and Originalz ft. Jannik, AiDN™, nuclear silo
  107 "store_item_hats_no_thirdpersion.smx"
  108 "Store Custom Weapon Models" (3.0) by Mr.Derp & Franc1sco franug | Zephyrus Store Module & bbs.93x.net
  109 "Admin Help" (1.10.0.6510) by AlliedModders LLC
  110 "SM Fortnite Emotes Extended" (1.4.2fix) by Kodua, Franc1sco franug, TheBO$$, crashzk
  111 "Steam Works Group Manager" (1.9fix) by Someone, crashzk
Errors:
levels_ranks/levelsranks_exstats_geoip.smx ([LR] Module - ExStats GeoIP): Native "GeoipCity" was not found
```

**Comment by nuclearsilo583** [comment]
Fixed. Please re-compile store.sp

**Comment by crashzk** [comment]
Hi, sorry for the delay... I tested it there and apparently the problem still occurs.
```
L 09/07/2021 - 00:00:20: [SM] Exception reported: Invalid timer handle ca9d48d5 (error 3)
L 09/07/2021 - 00:00:20: [SM] Blaming: store.smx
L 09/07/2021 - 00:00:20: [SM] Call stack trace:
L 09/07/2021 - 00:00:20: [SM]   [0] KillTimer
L 09/07/2021 - 00:00:20: [SM]   [1] Line 486, D:\Mega\Reddington\ARENA 1V1\addons\sourcemod\scripting\include\zephstocks.inc::ClearTimer
L 09/07/2021 - 00:00:20: [SM]   [2] Line 3718, D:\Mega\Reddington\ARENA 1V1\addons\sourcemod\scripting\store.sp::Store_DisconnectClient
L 09/07/2021 - 00:00:20: [SM]   [3] Line 1366, D:\Mega\Reddington\ARENA 1V1\addons\sourcemod\scripting\store.sp::OnClientDisconnect
L 09/07/2021 - 00:00:21: Error log file session closed.
L 09/07/2021 - 00:21:44: SourceMod error session started
L 09/07/2021 - 00:21:44: Info (map "am_multimap2_newlands") (file "/home/clientes/OGP_User_Files/whmcs/5703/csgo/addons/sourcemod/logs/errors_20210907.log")
L 09/07/2021 - 00:21:44: [SM] Exception reported: Invalid timer handle 9f694993 (error 1)
L 09/07/2021 - 00:21:44: [SM] Blaming: store.smx
L 09/07/2021 - 00:21:44: [SM] Call stack trace:
L 09/07/2021 - 00:21:44: [SM]   [0] KillTimer
L 09/07/2021 - 00:21:44: [SM]   [1] Line 486, D:\Mega\Reddington\ARENA 1V1\addons\sourcemod\scripting\include\zephstocks.inc::ClearTimer
L 09/07/2021 - 00:21:44: [SM]   [2] Line 3718, D:\Mega\Reddington\ARENA 1V1\addons\sourcemod\scripting\store.sp::Store_DisconnectClient
L 09/07/2021 - 00:21:44: [SM]   [3] Line 1366, D:\Mega\Reddington\ARENA 1V1\addons\sourcemod\scripting\store.sp::OnClientDisconnect
L 09/07/2021 - 00:22:14: [SM] Exception reported: Invalid timer handle a733497c (error 3)
L 09/07/2021 - 00:22:14: [SM] Blaming: store.smx
L 09/07/2021 - 00:22:14: [SM] Call stack trace:
L 09/07/2021 - 00:22:14: [SM]   [0] KillTimer
L 09/07/2021 - 00:22:14: [SM]   [1] Line 486, D:\Mega\Reddington\ARENA 1V1\addons\sourcemod\scripting\include\zephstocks.inc::ClearTimer
L 09/07/2021 - 00:22:14: [SM]   [2] Line 3718, D:\Mega\Reddington\ARENA 1V1\addons\sourcemod\scripting\store.sp::Store_DisconnectClient
L 09/07/2021 - 00:22:14: [SM]   [3] Line 1366, D:\Mega\Reddington\ARENA 1V1\addons\sourcemod\scripting\store.sp::OnClientDisconnect
```

**sm plugins list**
```
[SM] Listing 112 plugins:
  001 "Store - Trade System" (1.0) by Zephyrus
  002 "Rock The Vote" (1.10.0.6510) by AlliedModders LLC
  003 "CS:GO Multi1v1: Noscope round addon" (1.2.6) by Cruze
  004 "ServerAdvertisements3" (3.1.4) by ESK0
  005 "Server redirect" (1.3.1) by GAMMA CASE
  006 "Store - Dice gamble module" (1.2) by shanapu, nuclear silo
  007 "SM Franug Hats" (3.3.3) by Franc1sco franug
  008 "TecnoHard™ Ranks/Coins/Profiles" (1.1.0) by abnerfs
  009 "Store - Jackpot gamble module" (1.2) by shanapu, nuclear silo
  010 "Weapons & Knives" (1.7.3) by kgns | oyunhost.net
  011 "Fix Disconnect Reason" (1.0.0) by FroidGaming.net
  012 "Store Giveaway" (1.2) by nuclear silo
  013 "SourceBans++ Report Plugin" (1.7.0) by RumbleFrog, SourceBans++ Dev Team
  014 "Store - Bulletsparks item module" (1.0) by shanapu, nuclear silo
  015 "[ ZK Servidores™ ] Console Ads" (1.1) by biielzk, crashzk
  016 "Store - MVP sound item module" (1.0) by shanapu, nuclear silo
  017 "SM First Person View Models Interface" (3.2) by Franc1sco franug
  018 "[ANY] Chat Responder" (1.3.4) by Headline
  019 "SourceBans++ Discord" (1.7.0-49) by Kotik. Fork of RumbleFrog, SourceBans++ Dev Team.
  020 "Store - Player Skin Module (No ZR version)" (1.0) by nuclear silo
  021 "SourceBans++: SourceComms" (1.7.0) by Alex, SourceBans++ Dev Team
  022 "Basic Comm Control" (1.10.0.6510) by AlliedModders LLC
  023 "[Levels Ranks] Core" (v3.1.7 Beta 1) by RoadSide Romeo & Wend4r
  024 <Failed> "[LR] Module - ExStats GeoIP" (v3.1) by RoadSide Romeo
  025 "[LR] Module - Unusual Kills" (v3.1.6 SR2) by Wend4r
  026 "[LR] Module - ExStats Maps" (3.1 F1) by RoadSide Romeo
  027 "[LR] Module - ExStats Weapons" (v3.1) by RoadSide Romeo & Wend4r
  028 "[LR] Module - ExStats Hits" (v3.1) by Wend4r
  029 "[LR] Module - TOP by KDR" (v3.1.5) by Wend4r
  030 "Nextmap" (1.10.0.6510) by AlliedModders LLC
  031 "Store - Tracers Module" (1.0) by nuclear silo
  032 "CS:GO Multi1v1" (1.1.10-dev+220) by splewis
  033 "[ ZK Servidores™ ] High Ping Kicker" (1.1) by Dr. Api, crashzk
  034 "Map Nominations" (1.10.0.6510) by AlliedModders LLC
  035 "SwapTeam" (1.2.6fix) by MistaGee, Rogue, crashzk
  036 "Fix Hint Color Messages" (1.2.2 Franc1sco franug github version) by Phoenix (˙·٠●Феникс●٠·˙)
  037 "MapChooser" (1.10.0.6510) by AlliedModders LLC
  038 "AFK Manager" (4.3.0fix) by Rothgar
  039 "Store - Sound item module" (1.1) by shanapu, nuclear silo
  040 "SourceBans++: Admin Config Loader" (1.7.0) by AlliedModders LLC, SourceBans++ Dev Team
  041 "AntiDLL Handler" (1.7) by JDW
  042 "Store - Link item module" (1.0) by shanapu, nuclear silo
  043 "Store - Toplists module" (1.0) by shanapu, nuclear silo
  044 "Basic Commands" (1.10.0.6510) by AlliedModders LLC
  045 "[DHooks] Block SM Plugins" (1.0.0) by Bara
  046 "SM Franug CSGO Sprays" (1.4.2) by Franc1sco Steam: franug, EMINEM
  047 "SM FPVMI - Custom Weapons Menu" (3.1) by Franc1sco franug
  048 "eItems" (0.10) by ESK0 (Original author: SM9)
  049 "Gloves" (1.0.5) by kgns | oyunhost.net
  050 "CS:GO Multi1v1: flashbangs addon" (1.1.10-dev+220) by splewis
  051 "Store - The Resurrection with preview rewritten compilable with SM 1.10 new syntax" (5.5.8) by Zephyrus, nuclear silo
  052 "[CS:GO] Weapon Stickers" (1.0.18) by quasemago and donut1k
  053 "SourceBans++: Bans Checker" (1.7.0) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  054 "CS:GO Multi1v1: He grenade battle round addon" (1.1) by Franc1sco franug
  055 "Sound Commands" (1.10.0.6510) by AlliedModders LLC
  056 "Store Grenade Skin" (1.0) by zephyrus, nuclear silo
  057 "Store - Admin / Vip Flags Fore Store" (1.0) by nuclear silo
  058 "Skybox" (1.01) by Deathknife
  059 "Chat-Processor" (2.2.3) by Drixevel
  060 "Store - Bullet impact item module" (1.0) by shanapu, nuclear silo
  061 "Store - Teambet gamble module" (1.1) by shanapu, nuclear silo
  062 "SourceBans++: Main Plugin" (1.7.0) by SourceBans Development Team, SourceBans++ Dev Team
  063 "Store - Roulette gamble module" (1.2) by shanapu, nuclear silo
  064 "Store - Crash gamble module" (2.1) by Emur, AiDN™, nuclear silo
  065 "[CSS/CS:GO] AbNeR ResetScore" (1.5fix) by AbNeR_CSS
  066 "Fun Commands" (1.10.0.6510) by AlliedModders LLC
  067 "store_item_lasersight.smx"
  068 "Thirdperson Mode" (1.0) by Zephyrus
  069 "CS:GO Multi1v1: knife round addon" (1.1.10-dev+220) by splewis
  070 "Store - Pet item module" (1.0) by nuclear silo
  071 "Admin Menu" (1.10.0.6510) by AlliedModders LLC
  072 "Valve items menu" (1.0) by Franc1sco franug
  073 "Store - Particle item module" (1.0) by shanapu, nuclear silo
  074 "Store - Crowns gamble module" (1.2) by shanapu, nuclear silo
  075 "[CS:GO] Custom MVP Anthem" (1.11) by Kento
  076 "NoBots Enforcer" (1.0) by Nikooo777
  077 "[SWGM] Command Listener" (1.2fix) by Someone, crashzk
  078 "Simple Stealth" (1.0) by Potatoz
  079 "Basic Info Triggers" (1.10.0.6510) by AlliedModders LLC
  080 "Anti-Flood" (1.10.0.6510) by AlliedModders LLC
  081 "Player Commands" (1.10.0.6510) by AlliedModders LLC
  082 "[ANY] Unrestricted FOV" (1.2.0) by Dr. McKay
  083 "Client Preferences" (1.10.0.6510) by AlliedModders LLC
  084 "Store Grenade Trail" (1.0) by zephyrus, nuclear silo
  085 "SM Voice Agents Enabler" (1.0) by Franc1sco franug
  086 "Store - Hats Module" (1.0) by nuclear silo
  087 "Store - Lootbox module" (1.5) by shanapu, nuclear silo
  088 "Admin File Reader" (1.10.0.6510) by AlliedModders LLC
  089 "Store - Colored Smoke Module" (1.0) by nuclear silo
  090 "SourceBans++: SourceSleuth" (1.7.0) by ecca, SourceBans++ Dev Team
  091 "[Lilac] Little Anti-Cheat" (1.7.1) by J_Tanzanite
  092 "[ANY] Gifts" (2.3) by Zephyrus
  093 "Basic Chat" (1.10.0.6510) by AlliedModders LLC
  094 "Store - Tracers Module" (1.0) by nuclear silo
  095 "Store - Chat Processor item module with Scoreboard Tag" (1.2) by nuclear silo, Mesharsky, AiDN™
  096 "Fun Votes" (1.10.0.6510) by AlliedModders LLC
  097 "Store - Info panel item module" (1.0) by shanapu, nuclear silo
  098 "Store - Voucher module" (1.2) by shanapu, nuclear silo
  099 "SM Franug CS:GO Agents Chooser" (1.2) by Franc1sco franug & Romeo
  100 "[Multi-1v1] Challenge" (1.1.5) by Headline
  101 "store_item_sprays.smx"
  102 "[CS:GO] Music Kits Valve" (1.9.1) by iEx, Kento, crashzk, northeaster, ByDexter, Emur
  103 "Store - Coinflip gamble module" (1.2) by shanapu, nuclear silo
  104 "Store - Bunny module" (1.0) by nuclear silo
  105 "Basic Votes" (1.10.0.6510) by AlliedModders LLC
  106 "[CSGO]Multi 1v1 - Deagle 1 Tap" (1.0) by S4muRaY'
  107 "Blackjack" (1.0) by HerrMagic and Originalz ft. Jannik, AiDN™, nuclear silo
  108 "store_item_hats_no_thirdpersion.smx"
  109 "Store Custom Weapon Models" (3.0) by Mr.Derp & Franc1sco franug | Zephyrus Store Module & bbs.93x.net
  110 "Admin Help" (1.10.0.6510) by AlliedModders LLC
  111 "SM Fortnite Emotes Extended" (1.4.2fix) by Kodua, Franc1sco franug, TheBO$$, crashzk
  112 "Steam Works Group Manager" (1.9fix) by Someone, crashzk
Errors:
levels_ranks/levelsranks_exstats_geoip.smx ([LR] Module - ExStats GeoIP): Native "GeoipCity" was not found
```

**Comment by nuclearsilo583** [comment]
fixed. Please update scripting/include/zephstocks.inc and re-install store.sp

**Comment by crashzk** [comment]
Thank you, I compiled the new version and send it to the server, any problems I'll contact you again.
